### ISSUE TITLE
references

### ISSUE THREAD

**Issue by jsta** [lucasvenez/precintcon#2]
I see you have a `REFERENCES` file. Did you have any plans to cite these references within the function documentation? I was going to submit a pull request adding a citation to the `rai` documentation.

**Comment by jsta** [comment]
The reference you have tagged as _rai_ does not match the `rai` method used in this package. `rai` uses the method of:
> Van Rooy, M. P. "A rainfall anomaly index independent of time and space." Notos 14.43 (1965): 6.

while the reference uses a simple normalization procedure (subtract mean and divide by standard deviation).

**Comment by lucasvenez** [comment]
Thanks @jsta!

The `rai` reference was updated.
